### ISSUE TITLE
Selection dialog doesn't end after releasing `ctrl` key

### ISSUE THREAD

**Issue by Munto** [eldargab/LT-AltTab#1] opened 2015-12-21 03:57 UTC
This is exactly the feature I was looking for.
Unfortunately it doesn't work as expected, I have to click on the tab I want to switch to in the selection dialog.
It makes this plugin pretty useless :/

I'm using it with LightTable 0.8.0
It's a fresh install of LightTable and I installed the plugin via the plugin manager.
I restarted LT after the installation of the plugin but it didn't fix the behavior

**Comment by eldargab** [comment] 2015-12-21 06:36
Pretty weird. I'll try to reproduce, but can't promise it will be soon... Could you look at this yourself?

**Comment by eldargab** [comment] 2016-01-10 05:34
I was unable to reproduce, closing until someone else confirms the issue.

**Comment by dvtomas** [comment] 2016-03-11 11:04
I'm confirming the issue, LT 0.8.1, AltTab 0.2.0 also installed via the plugin manager. Exactly the same behavior as @Munto describes. Openbox 3.6.1 @ Debian. 

I really lone for this plugin, such a pity it doesn't work :)

**Comment by Munto** [comment] 2016-03-13 23:58
Hi @dvtomas !
I'm glad to not be alone :)
Strange coincidence, I use LXDE/Openbox on my machines too.

**Comment by dvtomas** [comment] 2016-03-14 07:10
I've just tried pekwm instead of openbox, to see if the WM might be the culprit, but the behavior is the same. I don't have any more window managers installed to try out.

**Closed as completed** 2016-03-14 07:22 UTC

**Comment by eldargab** [comment] 2016-03-14 07:44
The reason was about `KeyboardEvent.keyIdentifier` property having different value on linuxes. 
You can get the fix now by cloning repo to your `plugins` directory or wait for LightTable/plugin-metadata#49  to update normally via plugin manager.

**Comment by dvtomas** [comment] 2016-03-14 07:46
Awesome. I'll wait. Thank you so much!

**Comment by dvtomas** [comment] 2016-03-16 09:44
It works perfectly now, thank you so much.
Btw, the backward cycle is a little bit unusual. I'd expect

`Ctrl-tab` to cycle forward
`Ctrl-Shift-tab` to cycle backward.

However, it behaves this way:

`Ctrl-tab` cycles forward
When the list of tabs is opened via `Ctrl-tab`, the way to cycle back is
- hold `Ctrl`
- release `Tab`
- just press `Shift` alone repeatedly to cycle back. I can alter this with pressing `Tab` to cycle forward.

When I keep holding `Ctrl`, but also press `Shift` and then repeatedly press `Tab`, it seems to invoke the old behavior - your list selections is not updated at all, but the tabs are being switched in LT as if this key combination was dispatched directly to the LT tabs. Also, your list loses focus and I have to manually click some of the items to close it.

However, I much prefer your (perhaps unintentional) behavior to the original one (I hate pressing three keys at the same time), so, please, keep it :)

**Comment by eldargab** [comment] 2016-03-16 11:53
`Ctrl-Shift` behavior is intended. However `Ctrl-Shift-Tab` is indeed a kind of bug. Since this key combination is not defined in AltTab dialog itself, LT dispatches it further where it is binded to `:tabs.prev`,
and since `:tabs.prev` messes AltTab's state no wonder that we see strange things.
Perhaps I should do something about this next time, thanks for pointing out.
